import type { Handle } from '@sveltejs/kit';
import { getConfig } from '$lib/server/config';

/**
 * Browser features the app never uses. Denying them here means an injected
 * script cannot reach for them either.
 */
const PERMISSIONS_POLICY = [
	'accelerometer=()',
	'autoplay=()',
	'camera=()',
	'display-capture=()',
	'geolocation=()',
	'gyroscope=()',
	'magnetometer=()',
	'microphone=()',
	'payment=()',
	'usb=()'
].join(', ');

/** One year, the minimum for preloading, with subdomains included. */
const HSTS = 'max-age=31536000; includeSubDomains';

/**
 * Security headers that are not part of the Content-Security-Policy (that one
 * is generated by SvelteKit from `kit.csp`, see `vite.config.ts`).
 *
 * Runs outside the session hook, so by the time the response comes back
 * `locals.user` is already resolved and can decide the caching rules.
 */
export const securityHeaders: Handle = async ({ event, resolve }) => {
	const response = await resolve(event);

	response.headers.set('X-Content-Type-Options', 'nosniff');
	response.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
	response.headers.set('Permissions-Policy', PERMISSIONS_POLICY);
	// Isolation from other origins. COOP keeps a foreign window that opened or
	// was opened by ours from holding a reference to it (sign-in goes through
	// full-page redirects, there are no popups to keep). CORP stops a foreign
	// page from pulling our responses in as images, scripts or media; nothing
	// outside this origin embeds them, and server-to-server calls of the
	// exchange API are not subject to it — it is enforced by browsers only.
	response.headers.set('Cross-Origin-Opener-Policy', 'same-origin');
	response.headers.set('Cross-Origin-Resource-Policy', 'same-origin');

	// Sending HSTS over plain HTTP is meaningless, and on a local http:// origin
	// it would pin the developer's browser to https for a year.
	if (getConfig().ORIGIN.startsWith('https://')) {
		response.headers.set('Strict-Transport-Security', HSTS);
	}

	// Anything rendered for a signed-in user is personal: keep it out of shared
	// caches and out of the browser's back/forward cache after sign-out.
	if (event.locals.user) {
		response.headers.set('Cache-Control', 'no-store');
	}

	return response;
};
